[package]
name = "kde_from_scratch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peroxide = { version = "0.35.1", features = ["plot"] }
rayon = "1.10.0"
